# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'

    - name: Install dependencies
      run:
        pip install pipenv

    - name: Build
      env:
        PIPENV_VENV_IN_PROJECT: "true"
      run: |
        echo 'Building...'
        pipenv install --dev
        python3 src/index.py

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'

    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install --dev
        pip install coverage

    - name: Check PATH
      run: echo $PATH

    - name: Test
      env:
        PIPENV_VENV_IN_PROJECT: "true"
      run: |
        echo 'Testing...'
        cd src
        pipenv run coverage run -m unittest discover tests
        pipenv run coverage html -d report_html

    - name: Upload HTML coverage report
      uses: actions/upload-artifact@v2
      with:
          name: coverage-report
          path: src/report_html
  
  notification:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install mailutils
      run: sudo apt-get install -y mailutils

    - name: Send Notification
      run: |
        echo 'Notification...'
        echo "email enviado" | mail -s "email enviado" gabriel.leal@gec.inatel.br